// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoYITUZjVMDJmPIabo1rUEjyGiH8-HUJw',
    appId: '1:710914851562:web:cab068a9f42ffb0cb78d93',
    messagingSenderId: '710914851562',
    projectId: 'wood-stockpile',
    authDomain: 'wood-stockpile.firebaseapp.com',
    storageBucket: 'wood-stockpile.appspot.com',
    measurementId: 'G-QTM79E20DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK3zZU03M1S7LSZkmc-XZNG6YxFpdezAI',
    appId: '1:710914851562:android:294a602ace597750b78d93',
    messagingSenderId: '710914851562',
    projectId: 'wood-stockpile',
    storageBucket: 'wood-stockpile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05zzBVRMQV3uB4Z6_AODMKZsyPD3KltQ',
    appId: '1:710914851562:ios:d65eb09d7a872f15b78d93',
    messagingSenderId: '710914851562',
    projectId: 'wood-stockpile',
    storageBucket: 'wood-stockpile.appspot.com',
    iosClientId: '710914851562-seipniuo3lf851vnvpsr17ov4r10nuk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminWood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05zzBVRMQV3uB4Z6_AODMKZsyPD3KltQ',
    appId: '1:710914851562:ios:94107a7b74e171acb78d93',
    messagingSenderId: '710914851562',
    projectId: 'wood-stockpile',
    storageBucket: 'wood-stockpile.appspot.com',
    iosClientId: '710914851562-klb4ul1hbrr9bqm4370ucaaefgtjml2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminWood.RunnerTests',
  );
}
