// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoYITUZjVMDJmPIabo1rUEjyGiH8-HUJw',
    appId: '1:710914851562:web:cab068a9f42ffb0cb78d93',
    messagingSenderId: '710914851562',
    projectId: 'wood-stockpile',
    authDomain: 'wood-stockpile.firebaseapp.com',
    storageBucket: 'wood-stockpile.appspot.com',
    measurementId: 'G-QTM79E20DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK3zZU03M1S7LSZkmc-XZNG6YxFpdezAI',
    appId: '1:710914851562:android:5459e73b2ea901cab78d93',
    messagingSenderId: '710914851562',
    projectId: 'wood-stockpile',
    storageBucket: 'wood-stockpile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05zzBVRMQV3uB4Z6_AODMKZsyPD3KltQ',
    appId: '1:710914851562:ios:5f93db68235a6c89b78d93',
    messagingSenderId: '710914851562',
    projectId: 'wood-stockpile',
    storageBucket: 'wood-stockpile.appspot.com',
    iosClientId: '710914851562-rv2f43dpg1h6di3q3caiidfdlg6j0m1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.woodStockpile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05zzBVRMQV3uB4Z6_AODMKZsyPD3KltQ',
    appId: '1:710914851562:ios:0b0b551b6e147531b78d93',
    messagingSenderId: '710914851562',
    projectId: 'wood-stockpile',
    storageBucket: 'wood-stockpile.appspot.com',
    iosClientId: '710914851562-n13f85q1aul5p81f2f1g2bh01k7t51bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.woodStockpile.RunnerTests',
  );
}
